import type { Metadata } from "next";
import Link from 'next/link';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthProvider} from '@/app/contexts/AuthContext';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
        <header className="m-3 bg-gray-200 rounded p-4 flex justify-between items-center">
            <h1>
              <Link href="/" className="logo">
                Trello Clone
              </Link>
            </h1>
            <div className="flex space-x-4">
              {/* Navigation links for Login and Register */}
              <Link href="/login" className="btn-secondary">
                Login
              </Link>
              <Link href="/register" className="btn-primary">
                Register
              </Link>
            </div>
          </header>
          <main className="m-3 bg-gray-100 rounded">{children}</main>
        </AuthProvider>
      </body>
    </html>
  );
}
